baseURL = "https://vaderjunior.github.io/HCI_IARVR_Blog/"
languageCode = "en-us"
title = "Ajays IARVR Site"
theme = "paper"
publishDir = "docs"

# Fix asset paths for GitHub Pages subfolder
canonifyURLs = true
relativeURLs = true

[caches]
  [caches.images]
    dir = ":cacheDir/images"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
